In [1]:
#Задание 1

import numpy as np
array_ = np.arange(9, -1, -1)
print(array_)

[9 8 7 6 5 4 3 2 1 0]


In [2]:
#Задание 2

import numpy as np

number = 10
matrix = np.diag(np.arange(number - 1, -1, -1), k=0)
sum = 0
for i in range(number):
    sum += matrix[i, i]
print(sum)

45


In [3]:
#Задание 3

import numpy as np
from numpy import linalg as la

mat_a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
mat_b = np.array([4, 12, -3])
solv = la.solve(mat_a, mat_b)
print(solv)
print(np.allclose(np.dot(mat_a, solv), mat_b))

[ 0.46666667  3.84444444 -5.55555556]
True


In [4]:
#Задание 4

import numpy as np
from numpy import linalg as la

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


def get_cos(user_a, user_b):
    a_length = la.norm(user_a)
    b_length = la.norm(user_b)
    return round(np.dot(user_a, user_b) / (a_length * b_length), 3)


max_cos = -1
for user in users_stats:
    cos = get_cos(next_user_stats, user)
    if max_cos < cos:
        max_cos = cos
        match_user = user
print(next_user_stats)
print(match_user)
print(max_cos)

[0 1 2 0 0 0]
[0 1 1 0 0 0]
0.949
